import { GENRES } from './genres';

export const SAMPLE_BOOKS = [
  {
    id: 1,
    title: 'Преступление и наказание',
    author: 'Федор Достоевский',
    year: 1866,
    genres: [GENRES.ROMAN, GENRES.CRIME, GENRES.PHILOSOPHY],
    tags: ['психология', 'совесть', 'искупление'],
    description:
      'Бедный студент Родион Раскольников совершает убийство старухи-процентщицы, чтобы проверить свою теорию о "праве имеющих", но в итоге сталкивается с невыносимыми муками совести и ищет путь к искуплению.',
    cover: '/covers/Fedor-Dostoevsky-Prestyplenie-i-nakazanie.jpg',
    content: '/books/преступление-и-наказание111.txt',
    featured: false,
    isNew: false,
    isPopular: true,
  },
  {
    id: 2,
    title: '1984',
    author: 'Джордж Оруэлл',
    year: 1949,
    genres: [GENRES.ANTIUTOPIA, GENRES.SATIRE],
    tags: ['тоталитаризм', 'пропаганда', 'контроль'],
    description:
      'Мрачное будущее под властью тоталитарного режима, где Большой Брат всегда наблюдает, а язык, память и личная свобода становятся инструментами политического контроля.',
    cover: '/covers/Jorge-Oryel-1984.jpg',
    content: '/books/Оруэлл-Джордж.-1984.txt',
    featured: false,
    isNew: false,
    isPopular: true,
  },
  {
    id: 3,
    title: 'Властелин колец',
    author: 'Дж. Р. Р. Толкин',
    year: 1955,
    genres: [GENRES.FANTASY_EPIC, GENRES.FANTASY_HIGH, GENRES.ADVENTURE],
    tags: ['Средиземье', 'квест', 'борьба добра и зла'],
    description:
      'Хоббит Фродо Бэггинс и его верные спутники отправляются в опасное путешествие через Средиземье, чтобы уничтожить древний артефакт абсолютной власти и остановить Темного Властелина.',
    cover: '/covers/Vlastelin-Colec.jpg',
    content: '/books/Дж. Р. Р. Толкин — Властелин колец.txt',
    featured: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 4,
    title: 'Сто лет одиночества',
    author: 'Габриэль Гарсиа Маркес',
    year: 1967,
    genres: [GENRES.MAGICAL_REALISM, GENRES.FAMILY_SAGA],
    tags: ['Макондо', 'семья Буэндиа', 'магический реализм'],
    description:
      'Сага о нескольких поколениях семьи Буэндиа, чья судьба неразрывно связана с мистическим городком Макондо и повторяющимся одиночеством.',
    cover: '/covers/Gabriel-Garcia-100let.jpg',
    content: '/books/Markes_Gabriel_Garsia_Sto_let_odinochestva.txt',
    featured: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 5,
    title: '451 градус по Фаренгейту',
    author: 'Рэй Брэдбери',
    year: 1953,
    genres: [GENRES.SOCIAL_SCI_FI, GENRES.ANTIUTOPIA, GENRES.PHILOSOPHY],
    tags: ['цензура', 'книги', 'общество будущего'],
    description:
      'История о пожарном Гае Монтэге, который в мире запрещенных книг перестает сжигать знания и начинает их спасать.',
    cover: '/covers/451-gradus-po-foringeity.jpg',
    content: '/books/Fahrenheit-451.txt',
    featured: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 6,
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    year: 1940,
    genres: [GENRES.ROMAN, GENRES.MAGICAL_REALISM, GENRES.SATIRE],
    tags: ['Москва', 'Воланд', 'вечная любовь'],
    description:
      'Визит Воланда и его свиты в Москву переворачивает жизнь горожан и дает шанс на спасение гениальному автору и его верной возлюбленной.',
    cover: '/covers/master-i-margarita-bulgakov.jpg',
    content: '/books/Булгаков-Михаил-Мастер-и-Маргарита.txt',
    featured: false,
    isNew: false,
    isPopular: true,
  },
  {
    id: 7,
    title: 'На Западном фронте без перемен',
    author: 'Эрих Мария Ремарк',
    year: 1929,
    genres: [GENRES.WAR_NOVEL, GENRES.ANTI_WAR, GENRES.REALISM],
    tags: ['Первая мировая война', 'окопная правда', 'потерянное поколение'],
    description:
      'История о вчерашних школьниках, которые сталкиваются с беспощадной реальностью Первой мировой войны и взрослеют внутри кровавого ада окопов.',
    cover: '/covers/Na-zapodnom-fronte-bez-peremen.jpg',
    content: '/books/Erig-maria-remark-na-zapadnom-fronte.txt',
    featured: true,
    isNew: false,
    isPopular: false,
  },
  {
    id: 8,
    title: 'Над пропастью во ржи',
    author: 'Джером Д. Сэлинджер',
    year: 1951,
    genres: [GENRES.CLASSIC_PROSE],
    tags: ['Холден Колфилд', 'взросление', 'одиночество'],
    description:
      'Роман о нескольких днях из жизни подростка Холдена Колфилда, который пытается понять себя, людей вокруг и болезненный переход во взрослый мир.',
    cover: '/covers/nad_propasiy_rji.jpg',
    content: '/books/nad-propastyu-vo-rzhi.txt',
    featured: true,
    isNew: false,
    isPopular: false,
  },
  {
    id: 9,
    title: 'Тихий Дон',
    author: 'Михаил Шолохов',
    year: 1940,
    genres: [GENRES.REALISM, GENRES.HISTORIC_ROMAN],
    tags: ['казачество', 'Гражданская война', 'эпопея'],
    description:
      '"Тихий Дон" - масштабная эпопея о трагедии казачества, любви и разрушительных исторических потрясениях начала XX века.',
    cover: '/covers/tihiy-don.jpg',
    content: '/books/Шолохов Михаил Александрович. Тихий Дон (Книги 1 и 2).txt',
    featured: true,
    isNew: false,
    isPopular: false,
  },
  {
    id: 10,
    title: 'Сага о Форсайтах',
    author: 'Джон Голсуорси',
    year: 1922,
    genres: [GENRES.REALISM, GENRES.FAMILY_SAGA],
    tags: ['Англия', 'семейная сага', 'собственность'],
    description:
      '"Сага о Форсайтах" - монументальный цикл о жизни буржуазной семьи, запертой в мире собственности, расчета и болезненной привязанности к красоте.',
    cover: '/covers/saga-forsaity.jpg',
    content: null,
    featured: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 11,
    title: 'Отверженные',
    author: 'Виктор Гюго',
    year: 1862,
    genres: [GENRES.REALISM, GENRES.HISTORIC_ROMAN],
    tags: ['Жан Вальжан', 'Франция', 'милосердие'],
    description:
      '"Отверженные" - грандиозная эпопея о судьбе беглого каторжника Жана Вальжана, силе человеческого духа и борьбе добра со злом.',
    cover: '/covers/gugo-otverjenie.jpg',
    content: '/books/Гюго Виктор. Отверженные - TheLib.Ru.txt',
    featured: true,
    isNew: false,
    isPopular: false,
  },
  {
    id: 12,
    title: 'Унесенные ветром. Том 1',
    author: 'Маргарет Митчелл',
    year: 1936,
    genres: [GENRES.ROMAN, GENRES.HISTORIC_ROMAN],
    tags: ['Скарлетт О`Хара', 'Гражданская война', 'любовь'],
    description:
      '"Унесенные ветром" - роман о судьбе южанки Скарлетт О`Хара, чья беспечная молодость обрывается с началом Гражданской войны в США.',
    cover: '/covers/vetrom.jpg',
    content: '/books/vetrom.txt',
    featured: false,
    isNew: false,
    isPopular: true,
  },
  {
    id: 13,
    title: 'Робинзон Крузо',
    author: 'Даниэль Дефо',
    year: 1719,
    genres: [GENRES.REALISM, GENRES.ADVENTURE],
    tags: ['необитаемый остров', 'выживание', 'приключения'],
    description:
      'История британского моряка, который после кораблекрушения оказывается на необитаемом острове и выживает благодаря труду, стойкости и изобретательности.',
    cover: '/covers/robinzon-kruzo.jpg',
    content: '/books/robinzon-kruzo.txt',
    featured: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 14,
    title: 'Божественная комедия',
    author: 'Данте Алигьери',
    year: 1320,
    genres: [GENRES.EPIC_POETRY],
    tags: ['Ад', 'Чистилище', 'Рай', 'Беатриче'],
    description:
      'Монументальная поэма, в которой автор проходит через Ад, Чистилище и Рай в поисках божественной истины и спасения.',
    cover: '/covers/comedia.jpg',
    content: '/books/Алигьери Данте. Божественная комедия.txt',
    featured: false,
    isNew: true,
    isPopular: false,
  },
];
