export const GENRES = {
  ROMAN: 'roman',
  CRIME: 'crime',
  ANTIUTOPIA: 'antiutopia',
  SATIRE: 'satire',
  FANTASY_EPIC: 'fantasy_epic',
  FANTASY_HIGH: 'fantasy_high',
  SOCIAL_SCI_FI: 'social_scifi',
  PHILOSOPHY: 'philosophy',
  MAGICAL_REALISM: 'magical_realism',
  CLASSIC_PROSE: 'classic_prose',
  WAR_NOVEL: 'war_novel',
  ANTI_WAR: 'anti_war',
  REALISM: 'realism',
  HISTORIC_ROMAN: 'historic_roman',
  EPIC_POETRY: 'epic_poetry',
  ADVENTURE: 'adventure',
  FAMILY_SAGA: 'family_saga',
  FRONTEND: 'frontend',
  BACKEND: 'backend',
  ALGORITHMS: 'algorithms',
  FANTASY: 'fantasy',
  ETC: 'etc',
};

export const GENRE_LABELS = {
  [GENRES.ROMAN]: 'Роман',
  [GENRES.CRIME]: 'Криминальный жанр',
  [GENRES.ANTIUTOPIA]: 'Антиутопия',
  [GENRES.SATIRE]: 'Сатира',
  [GENRES.FANTASY_EPIC]: 'Эпическое фэнтези',
  [GENRES.FANTASY_HIGH]: 'Высокое фэнтези',
  [GENRES.SOCIAL_SCI_FI]: 'Социальная фантастика',
  [GENRES.PHILOSOPHY]: 'Философский роман',
  [GENRES.MAGICAL_REALISM]: 'Магический реализм',
  [GENRES.CLASSIC_PROSE]: 'Классическая проза',
  [GENRES.WAR_NOVEL]: 'Военный роман',
  [GENRES.ANTI_WAR]: 'Антивоенный роман',
  [GENRES.REALISM]: 'Реализм',
  [GENRES.HISTORIC_ROMAN]: 'Исторический роман',
  [GENRES.EPIC_POETRY]: 'Эпическая поэма',
  [GENRES.ADVENTURE]: 'Приключения',
  [GENRES.FAMILY_SAGA]: 'Семейная сага',
  [GENRES.FRONTEND]: 'Frontend',
  [GENRES.BACKEND]: 'Backend',
  [GENRES.ALGORITHMS]: 'Алгоритмы',
  [GENRES.FANTASY]: 'Фэнтези',
  [GENRES.ETC]: 'Разное',
};

export const getGenreLabel = (key) => GENRE_LABELS[key] || key;
