export const GENRES = {
  ROMAN: 'roman',
  CRIME: 'crime',
  ANTIUTOPIA: 'antiutopia',
  SATIRE: 'satire',
  FANTASY_EPIC: 'fantasy_epic',
  FANTASY_HIGH: 'fantasy_high',
  SOCIAL_SCI_FI: 'social_scifi',
  PHILOSOPHY: 'philosophy',
  MAGICAL_REALISM: 'magical_realism',
  CLASSIC_PROSE: 'classic_prose',
  WAR_NOVEL: 'war_novel',
  ANTI_WAR: 'anti_war',
  REALISM: 'realism',
  HISTORIC_ROMAN: 'historic_roman',
  EPIC_POETRY: 'epic_poetry',
  ADVENTURE: 'adventure',
  FAMILY_SAGA: 'family_saga',
  FRONTEND: 'frontend',
  BACKEND: 'backend',
  ALGORITHMS: 'algorithms',
  FANTASY: 'fantasy',
  FAIRY_TALE: 'fairy_tale',
  DETECTIVE: 'detective',
  THRILLER: 'thriller',
  PHILOSOPHICAL_FICTION: 'philosophical_fiction',
  PSYCHOLOGICAL_FICTION: 'psychological_fiction',
  HISTORICAL_FICTION: 'historical_fiction',
  ROMAN_VOSPITANIYA: 'roman_vospitaniya',
  PHILOSOPHICAL_TRAGEDY: 'philosophical_tragedy',
  DRAMA: 'drama',
  GOTHIC_FICTION: 'gothic_fiction',
  SOCIAL_NOVEL: 'social_novel',
  SHORT_STORY_COLLECTION: 'short_story_collection',
  SCIENCE_FICTION: 'science_fiction',
  ETC: 'etc',
};

export const GENRE_LABELS = {
  [GENRES.ROMAN]: 'Роман',
  [GENRES.CRIME]: 'Криминальный жанр',
  [GENRES.ANTIUTOPIA]: 'Антиутопия',
  [GENRES.SATIRE]: 'Сатира',
  [GENRES.FANTASY_EPIC]: 'Эпическое фэнтези',
  [GENRES.FANTASY_HIGH]: 'Высокое фэнтези',
  [GENRES.DETECTIVE]: 'Детектив',
  [GENRES.THRILLER]: 'Триллер',
  [GENRES.SOCIAL_SCI_FI]: 'Социальная фантастика',
  [GENRES.PHILOSOPHY]: 'Философский роман',
  [GENRES.MAGICAL_REALISM]: 'Магический реализм',
  [GENRES.CLASSIC_PROSE]: 'Классическая проза',
  [GENRES.WAR_NOVEL]: 'Военный роман',
  [GENRES.ANTI_WAR]: 'Антивоенный роман',
  [GENRES.REALISM]: 'Реализм',
  [GENRES.HISTORIC_ROMAN]: 'Исторический роман',
  [GENRES.EPIC_POETRY]: 'Эпическая поэма',
  [GENRES.ADVENTURE]: 'Приключения',
  [GENRES.FAMILY_SAGA]: 'Семейная сага',
  [GENRES.FRONTEND]: 'Frontend',
  [GENRES.BACKEND]: 'Backend',
  [GENRES.ALGORITHMS]: 'Алгоритмы',
  [GENRES.FANTASY]: 'Фэнтези',
  [GENRES.FAIRY_TALE]: 'Сказка',
  [GENRES.PHILOSOPHICAL_FICTION]: 'Философская проза',
  [GENRES.HISTORICAL_FICTION]: 'Историческая литература',
  [GENRES.ROMAN_VOSPITANIYA]: 'Роман воспитания',
  [GENRES.PHILOSOPHICAL_TRAGEDY]: 'Философская трагедия',
  [GENRES.DRAMA]: 'Драма',
  [GENRES.GOTHIC_FICTION]: 'Готическая литература',
  [GENRES.SOCIAL_NOVEL]: 'Социальный роман',
  [GENRES.SHORT_STORY_COLLECTION]: 'Сборник рассказов',
  [GENRES.SCIENCE_FICTION]: 'Научная фантастика',
  [GENRES.PSYCHOLOGICAL_FICTION]: 'Психологическая проза',
  [GENRES.ETC]: 'Разное',
};

export const getGenreLabel = (key) => GENRE_LABELS[key] || key;